spring:
  application:
    name: castiel
  datasource:
    url: jdbc:postgresql://localhost:5432/Castiel-Erp
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  docker:
    compose:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  security:
    token:
      secret: Xn29K!s1A@oQzL$9KeRvJm
